// Core data model for the Seedance anime harness.
// Everything lives in one JSON document on disk (see lib/store.ts).

export type AspectRatio = "auto" | "21:9" | "16:9" | "4:3" | "1:1" | "3:4" | "9:16";
export type Resolution = "480p" | "720p" | "1080p";
export type ModelFamily = "seedance-2.0" | "seedance-2.0-fast" | "seedance-2.5";
export type ProviderName = "fal" | "ark" | "mock";

export type AssetKind = "character" | "location" | "style" | "prop";

export interface RefImage {
  id: string;
  /** File name inside data/refs/<assetId>/ */
  file: string;
  label: string;
  /** Include this ref when the asset is used in a shot. */
  useInVideo: boolean;
  /** Cached public URL after uploading to the provider's storage. */
  remoteUrl?: string;
  remoteUploadedAt?: string;
  /** Prompt used if the image was generated by the harness. */
  genPrompt?: string;
  width?: number;
  height?: number;
  createdAt: string;
}

export interface Asset {
  id: string;
  kind: AssetKind;
  name: string;
  /** Slug used in prompts as @tag, e.g. "aki" -> "@aki". */
  tag: string;
  /** Appearance lock: hair, eyes, outfit, build, age, distinguishing marks. */
  description: string;
  /** Voice / personality notes (used for dialogue direction). */
  notes?: string;
  refs: RefImage[];
  createdAt: string;
  updatedAt: string;
}

export interface Scene {
  id: string;
  order: number;
  title: string;
  /** Story context for this scene (not sent to the model unless a shot references it). */
  description?: string;
  /** Default location asset for shots in this scene. */
  locationId?: string;
}

export type ShotStatus = "draft" | "queued" | "running" | "done" | "failed";

export interface Shot {
  id: string;
  sceneId: string;
  order: number;
  title: string;
  /** Action + camera + dialogue. Use @tag to reference assets. */
  prompt: string;
  /** Explicit asset references (in addition to @tags found in the prompt). */
  assetIds: string[];
  /** Seconds, 4-15 for 2.0, up to 30 for 2.5. "auto" lets the model pick. */
  duration: number | "auto";
  aspectRatio?: AspectRatio; // falls back to project default
  resolution?: Resolution; // falls back to project default
  model?: ModelFamily; // falls back to project default
  generateAudio?: boolean; // falls back to project default
  seed?: number;
  /** Override: don't prepend the project style prompt. */
  omitStyle?: boolean;
  /** Take chosen for assembly. */
  selectedTakeId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export type TakeStatus = "queued" | "running" | "done" | "failed" | "cancelled";

export interface TakeRef {
  assetId: string;
  assetName: string;
  refId: string;
  /** 1-based index -> "@ImageN" */
  imageIndex: number;
  url: string;
}

export interface Take {
  id: string;
  shotId: string;
  n: number; // take number within the shot
  status: TakeStatus;
  provider: ProviderName;
  model: ModelFamily;
  endpoint: string;
  requestId?: string;
  resolvedPrompt: string;
  refs: TakeRef[];
  params: {
    duration: number | "auto";
    aspectRatio: AspectRatio;
    resolution: Resolution;
    generateAudio: boolean;
    seed?: number;
  };
  /** File name inside data/output/ once downloaded. */
  videoFile?: string;
  videoUrl?: string; // remote url from provider
  seedUsed?: number;
  durationSec?: number;
  error?: string;
  log?: string[];
  estCostUsd?: number;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  /** Free-text rating/notes from the director. */
  rating?: number;
  notes?: string;
}

export interface Project {
  name: string;
  /** Prepended to every shot prompt unless omitStyle. Anime look, line quality, palette, era. */
  stylePrompt: string;
  /** Extra guidance appended after the shot prompt (e.g. "no subtitles, no watermark"). */
  suffixPrompt?: string;
  provider: ProviderName;
  model: ModelFamily;
  aspectRatio: AspectRatio;
  resolution: Resolution;
  generateAudio: boolean;
  /** Max reference images to send per asset (per shot). */
  maxRefsPerAsset: number;
  /** Optional style-reference asset applied to every shot. */
  styleAssetId?: string;
  imageModel: string; // fal endpoint used to generate reference images
  createdAt: string;
  updatedAt: string;
}

export interface Db {
  version: 1;
  project: Project;
  assets: Asset[];
  scenes: Scene[];
  shots: Shot[];
  takes: Take[];
}

export interface Assembly {
  id: string;
  file: string;
  shotIds: string[];
  createdAt: string;
}
