// Core data model for typedream. One JSON document per project on disk (see lib/store.ts).

export type AspectRatio = "auto" | "21:9" | "16:9" | "4:3" | "1:1" | "3:4" | "9:16";
export type Resolution = "480p" | "720p" | "1080p";
export type ModelFamily = "seedance-2.0" | "seedance-2.0-fast" | "seedance-2.5";
export type ProviderName = "fal" | "ark" | "mock";

export type AssetKind = "character" | "location" | "style" | "prop";

export interface RefImage {
  id: string;
  /** File name inside <project>/refs/<assetId>/ */
  file: string;
  label: string;
  /** Include this ref when the asset is used in a shot. */
  useInVideo: boolean;
  /** Cached public URL after uploading to the provider's storage. */
  remoteUrl?: string;
  remoteUploadedAt?: string;
  /** Prompt used if the image was generated by typedream. */
  genPrompt?: string;
  createdAt: string;
}

export interface Asset {
  id: string;
  kind: AssetKind;
  name: string;
  /** Slug used in prompts as @tag, e.g. "aki" -> "@aki". */
  tag: string;
  /** Appearance lock: hair, eyes, outfit, build, age, distinguishing marks. */
  description: string;
  /** Voice / personality notes (not sent to the model). */
  notes?: string;
  refs: RefImage[];
  createdAt: string;
  updatedAt: string;
}

export interface Scene {
  id: string;
  order: number;
  title: string;
  /** Story context for this scene (not sent to the model). */
  description?: string;
  /** Default location asset for shots in this scene. */
  locationId?: string;
}

export interface Shot {
  id: string;
  sceneId: string;
  order: number;
  title: string;
  /** Action + camera + dialogue. Use @tag to reference assets. */
  prompt: string;
  /** Explicit asset references (in addition to @tags found in the prompt). */
  assetIds: string[];
  /** Seconds, 4-15 for 2.0, up to 30 for 2.5. "auto" lets the model pick. */
  duration: number | "auto";
  aspectRatio?: AspectRatio;
  resolution?: Resolution;
  model?: ModelFamily;
  generateAudio?: boolean;
  seed?: number;
  omitStyle?: boolean;
  selectedTakeId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export type TakeStatus = "queued" | "running" | "done" | "failed" | "cancelled";

export interface TakeRef {
  assetId: string;
  assetName: string;
  refId: string;
  /** 1-based index -> "@ImageN" */
  imageIndex: number;
  url: string;
}

export interface Take {
  id: string;
  shotId: string;
  n: number;
  status: TakeStatus;
  provider: ProviderName;
  model: ModelFamily;
  endpoint: string;
  requestId?: string;
  resolvedPrompt: string;
  refs: TakeRef[];
  params: {
    duration: number | "auto";
    aspectRatio: AspectRatio;
    resolution: Resolution;
    generateAudio: boolean;
    seed?: number;
  };
  /** File name inside <project>/output/ once downloaded. */
  videoFile?: string;
  videoUrl?: string;
  seedUsed?: number;
  error?: string;
  log?: string[];
  estCostUsd?: number;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  rating?: number;
  notes?: string;
}

export interface Project {
  id: string;
  name: string;
  /** Logline / synopsis. Shown on the project card; not sent to the model. */
  description: string;
  /** Prepended to every shot prompt unless omitStyle. */
  stylePrompt: string;
  /** Appended after the shot prompt (negatives, "no subtitles" etc). */
  suffixPrompt?: string;
  provider: ProviderName;
  model: ModelFamily;
  aspectRatio: AspectRatio;
  resolution: Resolution;
  generateAudio: boolean;
  /** Max reference images to send per asset (per shot). */
  maxRefsPerAsset: number;
  /** Optional style-reference asset applied to every shot. */
  styleAssetId?: string;
  /** fal endpoint used to generate reference images */
  imageModel: string;
  createdAt: string;
  updatedAt: string;
}

export interface Db {
  version: 1;
  project: Project;
  assets: Asset[];
  scenes: Scene[];
  shots: Shot[];
  takes: Take[];
}

/** Lightweight listing entry. */
export interface ProjectSummary {
  id: string;
  name: string;
  description: string;
  provider: ProviderName;
  model: ModelFamily;
  assets: number;
  scenes: number;
  shots: number;
  takesDone: number;
  takesActive: number;
  createdAt: string;
  updatedAt: string;
}
